### PR TITLE
Duplicate

### PR DESCRIPTION
**Pull request by ashley7295**
@quinzel25 

I think I should have went back into the master branch and then created this duplicate branch as it has both changes from my readStatus branch and this duplicate branch. I will do that for the next branch I create. 

Code is working for duplicate entries!

### CODE REVIEW

**Comment by quinzel25** [comment]
I think this code thinks that every entry is a duplicate cuz I can't seem to enter a book into the database

**Comment by ashley7295** [comment]
@quinzel25 Yes it does! I'm also going to go back in and fix whats in each branch.

**Comment by ashley7295** [comment]
@quinzel25 Alright everything should be fixed! switched to a try-except block and it's working as it should!

**Comment by quinzel25** [comment]
This is solid! I'm gonna go ahead and merge it!

**Pull request merged**
