### PR TITLE
Read status

### PR DESCRIPTION
**Pull request by ashley7295**
@quinzel25 I made sure to keep the status neutral depending on if they are changing to read or unread. Let me know if you think this print status should be more specific and indicate which book is being changed but I wasn't sure if that was necessary as the user is already indicating what book they are selecting to change before confirming. 

Let me know what you think! Thanks!

### CODE REVIEW

**Review by quinzel25 — COMMENTED** [review]
When I'm running the program whenever I add a new book it gives me the validation message regardless if it's a repeat or not and doesn't add the book. I'm not sure if it's just my computer but did it work for you?

**Comment by ashley7295** [comment]
@quinzel25 You're totally right. I went back in and checked and it is doing what you are describing. I will go back in and try again! Thanks!

**Comment by ashley7295** [comment]
@quinzel25 fixed code, this branch now only contains the print message for the read status change!

**Comment by quinzel25** [comment]
Everything looks okay! Im going to go ahead and merge

**Comment by quinzel25** [comment]
there was a conflict for some reason but I went ahead and solved it, it works still!

**Pull request merged**
